### ISSUE TITLE
Lock major versions of JS-rails gems

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow-commons#100]
https://github.com/department-of-veterans-affairs/caseflow-commons/blob/master/caseflow.gemspec#L27-L29
Lock `jquery-rails`, `d3-rails`, and `momentjs-rails` to the current major version. Also aws gems and d3-rails.

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
