### ISSUE TITLE
Caseflow::Stats returns incorrect value for median

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-commons#101]
https://github.com/department-of-veterans-affairs/caseflow-commons/blob/master/app/models/caseflow/stats.rb#L91 returns incorrect median value

Currently for [15, 30, 120,180, 240, 300] returns 180, where it should be 150.

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
