### ISSUE TITLE
Logo:  App Title:  Text when hovered over should be darker

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#11]
Currently when you hover over the app title it appears as a `gray-light` color.

![image](https://cloud.githubusercontent.com/assets/6335546/20285822/ec28038c-aa91-11e6-9818-c79841cd8dba.png)

It should be USWDS `gray`

![image](https://cloud.githubusercontent.com/assets/6335546/20285795/ce14b700-aa91-11e6-8818-a84533c89189.png)

**Comment by KHarshawat** [comment]
This should be consistent across all Caseflow apps.

**Comment by mmlumba** [comment]
1. Find the line `gem "caseflow"`within the `Gemfile` for any app (certification, efolder, feedback) and modify the line to look like the following:
`gem "caseflow", git: "https://github.com/department-of-veterans-affairs/caseflow-commons", ref: "8b0be5e"`
2. Run `bundle install`
3. Hover over the top left header in the app
4. Verify that the color for the header is `#5b616b`
5. Revert the `gem "caseflow"` line back to its original state

**Comment by astewarttistatech** [comment]
Hey @kierachell, I assigned this to you because I still have no admin privileges 🙄

**Comment by kierachell** [comment]
<img width="554" alt="screen shot 2017-02-03 at 13 50 43" src="https://cloud.githubusercontent.com/assets/18075411/22604197/7420f08a-ea18-11e6-8fbc-02850f499f22.png">
<img width="698" alt="screen shot 2017-02-03 at 13 51 06" src="https://cloud.githubusercontent.com/assets/18075411/22604198/742278ba-ea18-11e6-9784-130932bd1ac2.png">
<img width="856" alt="screen shot 2017-02-03 at 13 53 02" src="https://cloud.githubusercontent.com/assets/18075411/22604200/742714d8-ea18-11e6-8e9d-ae6fac5ec0b2.png">
<img width="986" alt="screen shot 2017-02-03 at 13 55 11" src="https://cloud.githubusercontent.com/assets/18075411/22604199/742606ce-ea18-11e6-9c72-60044876ff61.png">
👍
