### ISSUE TITLE
Refactor Metrics and Prometheus services out of Caseflow and eFolder

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-commons#110]
Now that Caseflow and eFolder share the logic for Prometheus and Metrics services, we can refactor them out to be shared across the apps:

- https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/576
- https://github.com/department-of-veterans-affairs/caseflow/issues/1212

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/11226
