### ISSUE TITLE
S3 Streamer | Implement multi-part upload for 5GB+ eFolders

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-commons#114]
# Description
Apparently we've hit a new size for eFolders: 5GB+ zipfile size and it's causing Sentry errors:
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/389/events/6780/

AWS has a multi-part upload that can allow us to stored 5TB files... why not?
http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu-ruby-sdk.html

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder
1. Find a document list that has 1000+ documents and _compressed_ size of 5GB+
1. Try to download
1. See it fail to save to S3
1. See Sentry error.

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Logs:
```
Aws::S3::Errors::EntityTooLarge

Your proposed upload exceeds the maximum allowed size
```

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/389/events/6780/

## Screenshots
**_Scenario 1 - [Damn]_**

- Doc count
```
Document.where(download_id: 39419).count
   (1.6ms)  SELECT COUNT(*) FROM "documents" WHERE "documents"."download_id" = $1  [["download_id", 39419]]
[2017-08-22 17:37:34 -0400]    (1.6ms)  SELECT COUNT(*) FROM "documents" WHERE "documents"."download_id" = $1  [["download_id", 39419]]
=> 1146
```
- And size
```
irb(main):040:0> sizes.sum / 2**20
=> 18465
```

That's 19GB uncompressed...

**Comment by lowellrex** [comment]
The issues raised in this ticket that are created on the caseflow-commons side of the house were fixed in [PR 124](https://github.com/department-of-veterans-affairs/caseflow-commons/pull/124). Closing this ticket out since the remaining work on the efolder side is captured in [efolder ticket 768](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/768).
