### ISSUE TITLE
Style:  All "black" titles and text should be USWDS gray-dark

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#12]
All titles and text in Caseflow should be USWDS `gray-dark` as designed. Right now they are pure black.

![image](https://cloud.githubusercontent.com/assets/6335546/20285977/a8c81e14-aa92-11e6-8176-b9d8b1634c3c.png)

vs 

![image](https://cloud.githubusercontent.com/assets/6335546/20285981/adc943e8-aa92-11e6-9ee3-edb24179e362.png)

We should never use pure black in any of our text. Read this to understand why. https://ianstormtaylor.com/design-tip-never-use-black

**Comment by mmlumba** [comment]
@KHarshawat I saw that we use pure black in other parts of the CSS also (not text):
```
img {
    box-shadow: 0 0 20px -5px rgba($color-black, .5);
...
```
```
&::before {
    content: ' ';
    background: rgba($color-black, .4);
...
```

Should those be changed to `gray-dark`?

**Comment by mmlumba** [comment]
@astewarttistatech @kierachell Instructions for testing:
Find the line `gem "caseflow"`within the `Gemfile` for any app (certification, efolder, feedback) and modify the line to look like the following:
`gem "caseflow", git: "https://github.com/department-of-veterans-affairs/caseflow-commons", ref: "9955a2c"`
Run `bundle install`
View the app in Dev and verify the app looks similar to above screenshots in PR #30 
(this is a little harder to do since the pure black and the gray dark colors look similar...so for extra verification confirm that the text has the hex code color `#323a45`)
Revert the `gem "caseflow"` line back to its original state

**Comment by kierachell** [comment]
Oh boy a lot of places to check! 😈 
**eFolder**
<img width="1034" alt="commons_black_font_efolder" src="https://cloud.githubusercontent.com/assets/18075411/21915361/76e9bbde-d907-11e6-8882-a6932a3ffe01.png">
<img width="469" alt="commons_black_font_efolder2" src="https://cloud.githubusercontent.com/assets/18075411/21915362/76ea1598-d907-11e6-9a20-124ea3af36db.png">
<img width="476" alt="commons_black_font_efolder3" src="https://cloud.githubusercontent.com/assets/18075411/21915363/76ee00f4-d907-11e6-83a5-0f0edb3ad222.png">
<img width="828" alt="commons_black_font_efolder4" src="https://cloud.githubusercontent.com/assets/18075411/21915360/76e9bba2-d907-11e6-996a-61be2f814eaf.png">
Looks good as far as text goes 👍

**Comment by kierachell** [comment]
**Certification** only one issue <see below>

<img width="371" alt="commons_black_font_certification3" src="https://cloud.githubusercontent.com/assets/18075411/21915948/0a6b2c32-d90b-11e6-8ec6-8f2d79e7cbf8.png">
@KHarshawat do the **Form 8** numbers need to be changed from `pure black`?

<img width="1070" alt="commons_black_font_certification1" src="https://cloud.githubusercontent.com/assets/18075411/21915945/0a67ab52-d90b-11e6-97e6-fcc2595d02eb.png">


<img width="487" alt="commons_black_font_certification2" src="https://cloud.githubusercontent.com/assets/18075411/21915947/0a6ae790-d90b-11e6-95c2-4fd88e507d95.png">

<img width="750" alt="commons_black_font_certification4" src="https://cloud.githubusercontent.com/assets/18075411/21915946/0a68f5c0-d90b-11e6-9c45-8585f196a681.png">
<img width="500" alt="commons_black_font_certification5" src="https://cloud.githubusercontent.com/assets/18075411/21915949/0a6c8b22-d90b-11e6-8530-d5434d2f1d24.png">
All the headings and bolded fonts are changed as far as I could see

**Comment by kierachell** [comment]
**Dispatch** looks good 👍 
<img width="1560" alt="commons_black_font_dispatch1" src="https://cloud.githubusercontent.com/assets/18075411/21916157/871360a0-d90c-11e6-92ed-e40d3356c63d.png">
<img width="500" alt="commons_black_font_dispatch2" src="https://cloud.githubusercontent.com/assets/18075411/21916158/87137f40-d90c-11e6-9d44-589c9efda398.png">
<img width="1000" alt="commons_black_font_dispatch3" src="https://cloud.githubusercontent.com/assets/18075411/21916160/871a246c-d90c-11e6-8aaf-30051819ea0d.png">
<img width="500" alt="commons_black_font_dispatch4" src="https://cloud.githubusercontent.com/assets/18075411/21916159/87142346-d90c-11e6-8a9a-27ff99869802.png">

**Comment by kierachell** [comment]
<img width="794" alt="commons_black_font_feedback" src="https://cloud.githubusercontent.com/assets/18075411/21932519/ef9ac610-d96e-11e6-99cb-898d637dbf73.png">

Feedback looking good 👍

**Comment by KHarshawat** [comment]
@kierachell all looks great. For the Form 8 numbers, yes these should have changed colors too.

**Comment by kierachell** [comment]
#32 should fix this (once it goes through)

**Comment by kierachell** [comment]
<img width="248" alt="commons_blackfont_form8" src="https://cloud.githubusercontent.com/assets/18075411/22027765/d96d0448-dca2-11e6-8f53-4812e5693daa.png">
+R
Looks awesome now. I am totally not oppressed by any "true black" font.
My man cave is shinning with the new "dark grey" style.
