### ISSUE TITLE
Dropdown menu options should not be links

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#13]
Currently, where we have dropdowns we list items with links: 

![image](https://cloud.githubusercontent.com/assets/6335546/20286127/497ff5f2-aa93-11e6-8d66-75b1786213c9.png)

Instead dropdown options should be highlighted on hover like the following mockup:

![image](https://cloud.githubusercontent.com/assets/6335546/20286391/8ed88992-aa94-11e6-9c5b-bb2832dc8479.png)

There's 15px of padding around all of the text. On hover the text is highlighted with a USWDS `gray ` background and the text turns white. The spacing between the list items is even.

**Comment by KHarshawat** [comment]
@mmlumba talk with me before implmenting this as I have newer designs.

**Comment by KHarshawat** [comment]
Fuller spec is here:

![image](https://cloud.githubusercontent.com/assets/6335546/21356429/94959600-c69f-11e6-8087-76a2526611d0.png)


Note that the width and height of the dropdown are scalable but the width should be a minimum of 215px.

**Comment by KHarshawat** [comment]
This should be used for all dropdown menus.

**Comment by nikitarockz** [comment]
@KHarshawat Are you ready for this one to move forward based on your last 2 comments?

**Comment by KHarshawat** [comment]
@nikitarockz yes!

**Comment by mmlumba** [comment]
@KHarshawat Do you want me to use the specs from your second comment?

**Comment by KHarshawat** [comment]
yes plz!

**Comment by mmlumba** [comment]
@KHarshawat Is the 32px height only for the text link or is it for the bullet point?

**Comment by mmlumba** [comment]
Per yesterday's discussion total height for the list item should be 33px and the hover should extend to the edges of the dropdown.

**Comment by mmlumba** [comment]
@astewarttistatech @kierachell This change is in Certification and eFolder. Feedback will be added shortly once the PR is merged

**Comment by astewarttistatech** [comment]
Tested in UAT | Not Implemented :eyes:

<img width="249" alt="screen shot 2017-02-01 at 10 12 56 am" src="https://cloud.githubusercontent.com/assets/23038505/22512475/1e42abfc-e867-11e6-8ef6-443e1a599d2c.png">

**Comment by astewarttistatech** [comment]
Works on UAT for Efolder/ not for Dispatch.

**Comment by astewarttistatech** [comment]
**PASSED**

Environment Tested in: UAT

Steps to Validate: 
1. Go to Caseflow/Efolder
2. Check the drop down and hover over the available options for spacing and highlighting 

Screenshots: 
<img width="270" alt="screen shot 2017-02-01 at 11 46 10 am" src="https://cloud.githubusercontent.com/assets/23038505/22519176/69e8948e-e87d-11e6-8d49-c9d299e44b8c.png">
