### ISSUE TITLE
Breaking up Caseflow Commons - a "common" sense approach

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-commons#143]
![image](https://user-images.githubusercontent.com/1596259/35361274-c9e3f6f6-012e-11e8-81a8-90f31027078a.png)

After furiously scouring caseflow commons to take inventory on all the amazing things it does for us. I've got a plan on how we can break it up to make a little bit more sense:

## Feature & Authentication support
- `feature_toggle.rb`
- `functions.rb`
- `logger.rb`

This is the trickiest group of logic to know what to do with. There is some other feature/authentication related code that is currently duplicated through the apps. There are a bunch of authentication features used in Caseflow that are not available in the other apps. We could bundle all of this in a gem, or we could try and make an authentication service that takes care of it. If we want a service, there are a decent number of other prerequisites we'd need to have done before that becomes a real option.

I think for now we may just want to keep these in Commons. 

## Caseflow Stats
- `stats.rb`
- `app/assets/javascripts/stats/*`

This is likely to be deprecated if we move to a newer shiner BI tool, but for now it would be easy enough to move all stats related stuff into it's own repo.

## eFolder/Document related stuff
- `s3_service.rb`
- `fakes/s3_service.rb`
- `document_types.rb`

We should move all interaction with the VBMS eFolder (including caching) to eFolder Express. This would serve as a model on how intra-Caseflow services interact. This would also eliminate the need to share document related logic.

## Frontend stuff
- style guide CSS `app/assets/stylesheets`
- Vanilla JS character counter `app/assets/javascripts/character_counter.js`

`CharacterCounter` should be moved to `caseflow-feedback`, the only app where it's still used. CSS should be moved to https://github.com/department-of-veterans-affairs/appeals-frontend-toolkit

## Caseflow Build Support
`tasks/*`

As we split stuff out into more and more repos, it's going to be increasingly nice to share our CI/build scripts.

**Comment by nickheiner-usds** [comment]
Excellent image. I'll comment on the rest tomorrow! :smile:

**Comment by mdbenjam** [comment]
Moving document related stuff to eFolder is A+. We need to move the other apps to use the eFolder API but this should be pretty easy now!

**Comment by amprokop** [comment]
Strong +1 on the frontend stuff.

**Comment by amprokop** [comment]
`Feature & Authentication support`

Agreed that this can stay in commons. FeatureToggle and Functions, at least, are two library-like modules and are reasonably isolated and well-tested.

**Comment by nickheiner-usds** [comment]
👍 on the frontend stuff.

If we have a CSS file in `./client/node_modules`, is it trivial to pull it in from the Rails asset pipeline?

**Comment by tejans24** [comment]
👍🏼 looks good

@NickHeiner we would have to add the path to the assets.paths for rails to find them.

**Comment by shanear** [comment]
> If we have a CSS file in ./client/node_modules, is it trivial to pull it in from the Rails asset pipeline?

Yeah, i think it gets even easier in rails 5.
