### ISSUE TITLE
Fix spec/models/stats_spec.rb 

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-commons#149]
This keeps failing as of caseflow-commons version 0.3.3
Failures:
  `1) Caseflow::Stats#values when no cached stat values exist calculates and caches values
     Failure/Error: expect(subject[:wonderful_things_happened]).to eq(4)
       expected: 4
            got: 2
       (compared using ==)
     # ./spec/models/stats_spec.rb:119:in `block (4 levels) in <top (required)>'`

https://travis-ci.org/department-of-veterans-affairs/caseflow-commons/builds/341990946

**Comment by alisan16** [comment]
Closing as this hasn't been updated in 2 years.
