### ISSUE TITLE
Make sure app branding is consistent across apps

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#19]
![image](https://cloud.githubusercontent.com/assets/6335546/21321008/061e6eb0-c5e1-11e6-9282-bc88146958ab.png)

![image](https://cloud.githubusercontent.com/assets/6335546/21321012/0af3068a-c5e1-11e6-8c8f-df59dffdc6c9.png)

![image](https://cloud.githubusercontent.com/assets/6335546/21321023/16083de2-c5e1-11e6-8369-4b9b9178a2da.png)

![image](https://cloud.githubusercontent.com/assets/6335546/21321027/1aa72ef8-c5e1-11e6-853d-2f826f865b65.png)

As you can see above, the application names used across Caseflow are very inconsistent. I'll lay out how these apps are supposed to look for all applications:

![image](https://cloud.githubusercontent.com/assets/6335546/21322302/856fe586-c5e6-11e6-974a-2246e0d52c6f.png)

- [x] Padding between logo and app name and the words in the app name is consistent - `15px` 
- [x] Colors/weights
 - .`cf-logo { color: gray-dark; font-weight: 700px; }`
 - `.cf-nav { color: gray; font-weight: normal; }`
- [x] Every sub-page should have a page title (e.g. "Joe Snuffy (222222222)" or "Unauthorized" or "Complete Electronic Form 8")
- [x] Application names and the specific page name should be separated by `&nbsp; &gt; &nbsp;`
 - e.g. `Certification &nbsp; &gt; &nbsp;   Unauthorized` 
 - which results in "**Caseflow** Certification  >  Unauthorized"
- [x] Every application has it's own logo. 
 - The colored part of the logo should always sit in front of the grey part (the eFolder eXpress example above is incorrect)
 - The colored part of the overlay should have a multiply transparency over the grey portion. Since these are SVGs, the way to accomplish this is by flattening the transparency and exporting the SVG. Attaching the eFolder express SVG below so it can be fixed.

[CF eFolder Express Logo-04.svg.zip](https://github.com/department-of-veterans-affairs/caseflow-commons/files/661725/CF.eFolder.Express.Logo-04.svg.zip)

Here's the relevant section of the style guide:

![image](https://cloud.githubusercontent.com/assets/6335546/21321077/49822bd8-c5e1-11e6-85ac-c324e7035552.png)

**Comment by KHarshawat** [comment]
Here's the detailed spec that summarizes what's above.

![image](https://cloud.githubusercontent.com/assets/6335546/21357341/c88b07a8-c6a2-11e6-9a97-c74a3e71c159.png)

**Comment by mmlumba** [comment]
@KHarshawat-gov There are certain pages that don't have a page title, such as the "Establish Claim" page in Dispatch:
<img width="1148" alt="screen shot 2017-02-14 at 8 37 48 am" src="https://cloud.githubusercontent.com/assets/4773320/22931005/f6a2e92a-f290-11e6-974f-bedb9d2bf834.png">
I'll talk to @lakohl about which pages should have which titles (if any).

**Comment by lakohl** [comment]
@KHarshawat would love to chat about page titles vs. say table titles. and if we might choose to style those differently. It's true that not all pages have titles and I would be in favor of adding them to help the user understand where they are. 
For example what @mmlumba understandably just referred to as the 'Establish Claim' page is really the caseworker landing page, there is another page where the claim actually gets established.

**Comment by KHarshawat-gov** [comment]
Interesting ... Ready to discuss @lakohl :)

**Comment by KHarshawat-gov** [comment]
All these headers are out of date. We now have the following pattern

[Icon] **Caseflow** `Application Name`

On the work queue page there doesn't need to be a page title.
On workflow pages we have the option of including the page title using the following format (the title should reflect any navigation, like progress bars, that are used in the app)

[Icon] **Caseflow** `Application Name` > `Page Title`

Alternately some pages can include the Veteran for the case that the user is actively working on the title using the following format

[Icon] **Caseflow** `Application Name` | `Page Title`

**Comment by kierachell** [comment]
Something I noticed about _Stats_ page:
![screenshot_2017-02-25_12-50-19](https://cloud.githubusercontent.com/assets/18075411/23333417/070665aa-fb59-11e6-9976-b83b6249041b.png)
eFolder lacks the _Dashboard_ in the header and has a big title instead
![screenshot_2017-02-25_12-50-10](https://cloud.githubusercontent.com/assets/18075411/23333416/070561b4-fb59-11e6-9fec-048bc490084d.png)

**Comment by kierachell** [comment]
The stats page will have a redo anyway so
**PASSED** for now.
