### ISSUE TITLE
Remove underline when using abbr tag

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#21]
Today we underline text with a dotted line when we use the `abbr` tag in html. We should remove this underline for all `abbr` tags.

![image](https://cloud.githubusercontent.com/assets/6335546/21359297/d02fe24c-c6a9-11e6-97ed-4ab86c36b1d9.png)

**Comment by mmlumba** [comment]
@astewarttistatech @kierachell Instructions for testing:
Find the line `gem "caseflow"`within the `Gemfile` for any app (certification, efolder, feedback) and modify the line to look like the following:
`gem "caseflow", git: "https://github.com/department-of-veterans-affairs/caseflow-commons", ref: "f186d50"`
Run `bundle install`
Verify that there is no dotted underline in the footer (see below screenshot)
<img width="355" alt="screen shot 2017-01-24 at 1 46 17 pm" src="https://cloud.githubusercontent.com/assets/4773320/22261632/a3c3542a-e23b-11e6-84ed-d17331ebcc5c.png">
Revert the `gem "caseflow"` line back to its original state

**Comment by kierachell** [comment]
<img width="403" alt="screen shot 2017-01-31 at 10 19 45" src="https://cloud.githubusercontent.com/assets/18075411/22470934/d4e50ba8-e79e-11e6-89bd-d07134f063f1.png">
Looks correct on Certification/Dispatch and Feedback (eFolder too,duh)
