### ISSUE TITLE
Clean up footer in Caseflow apps

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#22]
**Current state: **

![image](https://cloud.githubusercontent.com/assets/6335546/21359053/dc2c831c-c6a8-11e6-92b3-70b4c8bc7bbd.png)

![image](https://cloud.githubusercontent.com/assets/6335546/21359340/f8fd2162-c6a9-11e6-9ecb-ccda47cd88b7.png)

![image](https://cloud.githubusercontent.com/assets/6335546/21359425/44520470-c6aa-11e6-8088-c66ea3322fcb.png)

**Desired State:**

![footer](https://cloud.githubusercontent.com/assets/6335546/21359858/8f503356-c6ab-11e6-9fb1-bb232480c40c.png)

- [x] Make sure  HR is the same width as the app canvas.
- [x] Make sure there is always at least 30px b/t HR and buttons above it.
- [x] Make sure footer text is 17px
- [x] Remove period at the end of VA
- [x] fix underlines under abbr tag (see #21)
- [x] Make sure footer is always anchored to the bottom. Currently it is not and it's especially noticeable on message pages.

**Comment by slj** [comment]
The header needs more padding and its main menu should align right with the browser at certain widths, otherwise we have this:

![headerneedslove](https://cloud.githubusercontent.com/assets/1053255/22959422/3972a024-f304-11e6-8c2e-aef8b423f9ab.gif)

**Comment by kierachell** [comment]
This is what I like to see, some good old manual self-QAing 👍

**Comment by kierachell** [comment]
1. Needs a PR to add this to Caseflow Feedback
https://github.com/department-of-veterans-affairs/caseflow-feedback/
2. I am not seeing `50px` for padding below below for links in the footer `div` that contains the links/text
![footer50px](https://cloud.githubusercontent.com/assets/18075411/23076447/82343c30-f50e-11e6-8f49-1946e41d6d4d.png)

**Comment by slj** [comment]
@kierachell I've created a PR for @mmlumba's review that adds padding to the bottom: https://github.com/department-of-veterans-affairs/caseflow-commons/pull/50

Once approved.  I'll update PRs for cert/efolder/feedback.

**Comment by slj** [comment]
This PR https://github.com/department-of-veterans-affairs/caseflow-feedback/issues/113 will not build. I've tried several times via closing/re-opening the PR to no avail.

**Comment by slj** [comment]
Build succeeded.

**Comment by kierachell** [comment]
**PASSED**
lgtm
![feedbackfooter](https://cloud.githubusercontent.com/assets/18075411/23170308/b0aae9c2-f81c-11e6-80e5-9168d651844e.png)
