### ISSUE TITLE
Upgrade to new US Web Design Standards gem

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#23]
We should update our US Web Design Standards to the latest version (currently 0.14.0)

There is a new gem being used for USWDS:
https://github.com/18F/uswds-rails-gem

See https://github.com/18F/us_web_design_standards_gem/issues/15#issuecomment-203564667 for more information

**Comment by slj** [comment]
Things seem to work locally, but while changes to `caseflow-commons` and `efolder` pass the CI, `caseflow` fails.  Seems mostly to Capybara not being able to find certain elements.  No clue why right now.

**Comment by slj** [comment]
@kierachell or @astewarttistatech pls validate by going anywhere in the apps you choose.  As long as there are no glaring style errors or "missing component/asset" type errors, all is well.

**Comment by kierachell** [comment]
Well, there were...many.
So I need to know if this is staying or going
@shanear @slj @mdbenjam - we need a follow up issue for the fixes and updates related to this.
Right now the _functionality_ is there, but this:

<img width="1428" alt="screen shot 2017-03-01 at 9 41 36 am" src="https://cloud.githubusercontent.com/assets/18075411/23464618/a9e10138-fe63-11e6-83c2-b7ac45b1d06c.png">
