### ISSUE TITLE
Clean up FAQ Page template

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#25]
- [x] On this page the following should not have `margin:0`: `.usa-unstyled-list li { margin:0; }` 
- [x] We should add a divider between the questions and the answers below. The color of the divider should be `gray-light` and there should be 30px margin at the top and bottom of it

![image](https://cloud.githubusercontent.com/assets/6335546/21403864/a969bd84-c78c-11e6-843a-872536aeab76.png)
![image](https://cloud.githubusercontent.com/assets/6335546/21403889/c1348390-c78c-11e6-9c9e-5a82be59d9f3.png)

**Comment by mmlumba** [comment]
@KHarshawat-gov What is the padding between the `li` elements?

**Comment by KHarshawat-gov** [comment]
@mmlumba I'll come and we'll tweak in the dom

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate: 
1. Go to https://certification.cf.uat.ds.va.gov/
2. Validate the styling changes

Tested in UAT
Screenshots:
<img width="1333" alt="screen shot 2017-02-08 at 9 13 25 am" src="https://cloud.githubusercontent.com/assets/23038505/22740796/02727718-eddf-11e6-919d-97cbe7ef363a.png">
