### ISSUE TITLE
Tabs still not rendering consistently

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow-commons#49]
### Problem

When the `cf-tab` class is applied to `div`, `li` and `button` tags, the UI is inconsistent.

#### DIV tag
Use caseflow/cert:
- Select **Switch User** from main menu
- Under **Switch User** click **Establish Claim at station 283**
- Under **Dispatch** click **Establish Claim**
- Click **Establish Next Claim** button
- Under **Select a Decision Document** examine the Decision tabs

#### BUTTON tag
Use efolder:
- enter DEMO1 and click **Search**
- Download the discovered documents and examine the Progress/Completed/Error tabs

#### LI tag
Use efolder stats:
- visit http://localhost:3000/stats
- Examine the Hourly/Daily/Weekly/etc tabs

**Comment by kierachell** [comment]
It's whack, yo:
![efolderstats](https://cloud.githubusercontent.com/assets/18075411/23326827/af8f0f26-fad0-11e6-84e9-d6442abe3bc9.png)
and not consistent
![certstats](https://cloud.githubusercontent.com/assets/18075411/23326828/af930c20-fad0-11e6-8b37-bea6b159fada.png)

**Comment by slj** [comment]
What browser did you use?

**Comment by slj** [comment]
Locally things don't look as bad as this on any browser.  Nevertheless, I somehow pushed a fix where the the margin was off by 1px for BUTTON and LI...SMH...I'll make the change and put some screenshots of IE9, FF and Chrome later today.

**Comment by slj** [comment]
OK, I was able to re-create the stats page problem on Chrome locally.  I don't understand how this happened.  There's no way I would have knowingly pushed a commit if the results were like this.  Frustrated, but will persist until this is truly resolved.

**Comment by kierachell** [comment]
This is on IE11 from `dev` and `uat`.

**Comment by slj** [comment]
@kierachell based on the results I posted, can this go back into validation?
