### ISSUE TITLE
Header | Application Name and Icon Spacing

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-commons#56]
connects #19 

Currently the App name and Icon are not aligned consistently across the apps:
It shifts left/right between different apps.
And the spacing between the text and icon is inconsistent
![headersize](https://cloud.githubusercontent.com/assets/18075411/23232108/1ed7cfe0-f918-11e6-8341-5627c0f33f8c.gif)

**Note:** The spacing for the icon from the left seems to OK most of the time; but it will randomly shift at different zoom levels: e.g. it is stable across pages at 100% but at 120% it would shift around as shown above;

We need styling directions on the:
- icon position
- text spacing
- text styling for Help/Application Name/Etc

**Comment by gnakm** [comment]
I'm going to close out this issue because it is being address here https://github.com/department-of-veterans-affairs/caseflow/issues/1086 for the living styleguide. In this issue, you will find a link to invision with the specs.
