### ISSUE TITLE
Use Javascript assets in USWDS gem to remove components.js dependency

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow-commons#57]
Currently the file `components.js` in `vendors/assets/javascripts` of the Caseflow repo adds the accordions to the Caseflow style guide. Ideally we would like to remove this file and add all the necessary JS to caseflow-commons.

Connects #23

**Comment by mmlumba** [comment]
For Validation:
Check if the accordions on both styleguide and Reader still work as expected

**Comment by astewarttistatech** [comment]
**PASSED**

Env: UAT
Browser: FF and Chrome 

Steps to Validate: 
1. Access Styleguide 
2. Verify that the accordions work accordingly (get the pun)
3. Navigate to a document in Reader
4. Check the menu's accordions to see if they work like the ones in the styleguide  

Screenshots:
![accordiansyeah](https://user-images.githubusercontent.com/23038505/29221107-849d5c3e-7e8b-11e7-93fc-ee7c5fe32b06.gif)
