### ISSUE TITLE
Use block text for checkboxes and radios

### ISSUE THREAD

**Issue by slj** [department-of-veterans-affairs/caseflow-commons#66]
This is likely documented elsewhere, nevertheless, these:

![radio-before](https://cloud.githubusercontent.com/assets/1053255/23813970/6cff7620-05af-11e7-8619-bebf35e0dcbc.gif)

<img width="265" alt="chk-before-50" src="https://cloud.githubusercontent.com/assets/1053255/23814280/e4fbdc44-05b0-11e7-8328-a86c78c9f9de.png">

Should work like these:

![radio-after](https://cloud.githubusercontent.com/assets/1053255/23813982/7fe18f12-05af-11e7-8008-2a6f3c87b2ba.gif)

<img width="237" alt="chk-after-50" src="https://cloud.githubusercontent.com/assets/1053255/23814287/e9d2b08a-05b0-11e7-8097-4f93a530f393.png">

**Comment by kierachell** [comment]
**PASSED**
