### ISSUE TITLE
"Continue" button too close to modal

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow-commons#81]
**Description**

Currently in Certification V2, on the all the pages applicable in the flow, the "Continue" button is laying on the border of the modal. 

**Expectation: **
Minor spacing between buttons and the modal border (Shelly can you add specs here?)

**Steps to Recreate: **
1. In Certification V2, navigate to the Confirm Page Details page and validate that the "Continue" button is too close to the border of the modal and the same goes for the rest of the flow.

**Screenshots:**
<img width="963" alt="screen shot 2017-04-19 at 9 35 16 am" src="https://cloud.githubusercontent.com/assets/23038505/25183284/28e02e3a-24e5-11e7-8ffd-54c57afd7e12.png">

**Comment by amprokop** [comment]
@astewarttistatech — can you verify that this is still happening?

**Comment by amprokop** [comment]
Closing. This seems to have been fixed.
