### ISSUE TITLE
FeatureToggle | How to determine if a feature is `global-only`?

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-commons#98]
# Description
When trying to FeatureToggle for a specific user, the `enabled?` checks for User's regional office, which is not defined in eFolder. So, it's hard to tell if the feature even working for a user...

And you can't really enable/disable a feature globally to override user/RO-specific configurations

## Expected:
1. Be able to tell when a feature is `global-only`
1. Be able to "expand" a feature scope to global/RO without having to disable it first
1. eFolder to be able to access `regional_property` for a User.
1. Have a comprehensive list of features that exist, not just enabled.

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder console
1. Toggle feature for a user
1. Check if it is toggled
1. Find that user has no regional office.

**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [ ] Prod

## Logs:
```
FeatureToggle.enabled?(:vva_service, regional_offices: User.last)
  User Load (1.0ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
[2017-06-14 09:18:32 -0400]   User Load (1.0ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
ArgumentError: unknown keyword: regional_offices
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/bundler/gems/caseflow-commons-a9ffc8ea3a16/app/services/feature_toggle.rb:56:in `enabled?'
        from (irb):9
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

 -- Can't even globally enable!??!?!
```
FeatureToggle.enabled?(:vva_service)
=> false
irb(main):002:0> FeatureToggle.enable!(:vva_service)
=> true
irb(main):003:0> FeatureToggle.enabled?(:vva_service)
=> false
```

# Related Issues

**_Engineering_**
#487

**Comment by alisan16** [comment]
This hasn't been updated in 2 years. Closing.
